/* sw.js — service worker.
 *
 * The whole point: after one visit the app opens on the beach with the network
 * off. So the shell is precached on install and served cache-first forever;
 * anything else goes straight to the network and is never cached.
 *
 * The block below is generated by `npm run stamp` — VERSION is a hash of the
 * shell files, so editing any of them changes the cache name automatically and
 * `npm test` fails if the two have drifted apart. Do not edit it by hand.
 */

/* BEGIN GENERATED — npm run stamp */
const VERSION = "a631bb92decd";
const SHELL = [
  "./",
  "./css/app.css",
  "./fonts/atkinson-mono-400.woff2",
  "./fonts/atkinson-mono-500.woff2",
  "./fonts/atkinson-mono-600.woff2",
  "./fonts/atkinson-next-400.woff2",
  "./fonts/atkinson-next-500.woff2",
  "./fonts/atkinson-next-600.woff2",
  "./fonts/barlow-condensed-500.woff2",
  "./fonts/barlow-condensed-600.woff2",
  "./fonts/barlow-condensed-700.woff2",
  "./icon.svg",
  "./index.html",
  "./js/app.js",
  "./js/backend.js",
  "./js/calendar.js",
  "./js/db.js",
  "./js/devclock.js",
  "./js/devmode.js",
  "./js/handicap.js",
  "./js/pages/checklist.js",
  "./js/pages/dev.js",
  "./js/pages/home.js",
  "./js/pages/live.js",
  "./js/pages/registers.js",
  "./js/pages/results.js",
  "./js/pages/sequence.js",
  "./js/pages/setup.js",
  "./js/pages/signon.js",
  "./js/pages/standdown.js",
  "./js/pdf.js",
  "./js/pin.js",
  "./js/raceday.js",
  "./js/raceevents.js",
  "./js/registers.js",
  "./js/resume.js",
  "./js/router.js",
  "./js/scoring.js",
  "./js/state.js",
  "./js/supabase.js",
  "./js/sync.js",
  "./js/ui.js",
  "./js/update.js",
  "./js/wakelock.js",
  "./js/wind.js",
  "./manifest.json",
];
/* END GENERATED */

const CACHE = `nsc-race-day-${VERSION}`;

/* Absolute URLs of the shell, resolved against wherever this worker is served
   from — the app lives at /nsc-race-day/ on GitHub Pages and at / locally. */
const SHELL_URLS = new Set(SHELL.map((path) => new URL(path, self.registration.scope).href));
const INDEX_URL = new URL("./index.html", self.registration.scope).href;

self.addEventListener("install", (event) => {
  // Deliberately no skipWaiting() here. A new worker sits in "waiting" until
  // the OOD taps the update prompt, so the app can never swap itself out from
  // under someone mid-race. (The very first install has no worker to wait for
  // and activates straight away.)
  //
  // cache:"reload" bypasses the browser's HTTP cache. GitHub Pages serves
  // assets with max-age=600, so without it a new worker could happily
  // precache ten-minute-old copies of the files it was installed to replace.
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(SHELL.map((path) => new Request(path, { cache: "reload" }))))
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;

  // Never touch writes. Supabase pushes in Phase 2 must fail honestly when
  // offline so sync.js can retry them, not be silently swallowed here.
  if (request.method !== "GET") return;

  // Any navigation renders the one app shell; routing is client-side.
  if (request.mode === "navigate") {
    event.respondWith(cacheFirst(INDEX_URL));
    return;
  }

  const url = new URL(request.url);
  if (SHELL_URLS.has(url.href)) {
    event.respondWith(cacheFirst(url.href));
    return;
  }

  // Everything else: straight through, uncached.
});

async function cacheFirst(url) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(url);
  if (hit) return hit;
  try {
    const response = await fetch(url);
    if (response.ok) cache.put(url, response.clone());
    return response;
  } catch (err) {
    // Offline and not in cache. Nothing useful to say; let it fail.
    return Response.error();
  }
}

self.addEventListener("message", (event) => {
  // Sent by js/update.js when the OOD taps "tap to refresh".
  if (event.data === "skip-waiting") self.skipWaiting();
  // Lets the page show which build it is running.
  if (event.data === "version") event.source?.postMessage({ type: "version", version: VERSION });
});
